## YAML Template.
name: Buoy
main: com.mahn42.anhalter42.buoy.BuoyMain
version: 0.1
commands:
   buoy_list:
      description: List all buoys in the current world.
      usage: /buoy_list
      permission: buoy.list
      permission-message: You don't have permission
permissions:
    buoy.*:
        description: Gives access to all buoy commands
        children:
            buoy.list: true
    buoy.list:
        description: Allows you to list all buoys in the current world
        default: true